language: r
sudo: required

# https://docs.travis-ci.com/user/caching/#r-package-cache
cache: packages

env:
  - MAKEFLAGS="-j4"

addons:
  apt:
    packages:
      - libxml2-dev
      - tk-dev
      - libgit2-dev
      - libmagick++-dev

r:
  - devel
  - bioc-devel
  - release
  - bioc-release
  - 3.6.0

stages:
  - Setup Cache
  - Test

# setup cache first
jobs:
  include:
    - stage: Setup Cache
      r: bioc-devel
      script: true
      
    - stage: Setup Cache
      r: bioc-release
      script: true
      
    - stage: Setup Cache
      r: 3.6.0
      script: true

before_install:
  - tlmgr install index marginfix bera nowidow parnotes

install:
  - R --version
  - R -e 'if(!require("BiocManager")) install.packages("BiocManager")'
  - R -e 'if(!require("devtools")) install.packages("devtools", Ncpus=4)'
  - R -e 'BiocManager::install(Ncpus=4)'
  - R -e 'devtools::install_dev_deps(ask=FALSE, Ncpus=4)'

script:
  - R CMD build --keep-empty-dirs --no-resave-data .
  - R CMD check --no-vignettes --timings *tar.gz
  - R CMD BiocCheck *tar.gz
  - R -e 'devtools::run_examples()'
  - R -e 'devtools::test()'
  - cd vignettes && R CMD Sweave --engine=knitr::knitr --pdf *.Rnw
  
