# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_cpp_code <- function(a) {
    .Call('_test_ci_run_cpp_code', PACKAGE = 'test.ci', a)
}

